[package]
name = "sdk-core"
version = "0.1.0"
authors = ["Spencer Judge <spencer@temporal.io>", "Vitaly Arbuzov <vitaly@temporal.io>"]
edition = "2018"

[lib]

[dependencies]
async-trait = "0.1"
prost = "0.6"
prost-types = "0.6"
thiserror = "1.0"
tonic = "0.3"

[build-dependencies]
tonic-build = "0.3"